/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wangliang160616_androidtest_activity_EncryptActivity */

#ifndef _Included_com_wangliang160616_androidtest_activity_EncryptActivity
#define _Included_com_wangliang160616_androidtest_activity_EncryptActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wangliang160616_androidtest_activity_EncryptActivity
 * Method:    getEncryptString1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wangliang160616_androidtest_activity_EncryptActivity_getEncryptString1
  (JNIEnv *, jobject);

/*
 * Class:     com_wangliang160616_androidtest_activity_EncryptActivity
 * Method:    getEncryptString2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wangliang160616_androidtest_activity_EncryptActivity_getEncryptString2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
